### PR TITLE
Added ability to use custom grid and grid cell class names.

### LINKED ISSUE #3: Add ability to use custom class names.
It would be great is the class 'grid' and 'grid-cell' names could be customized by setting a variable. For instance, instead of the 'grid' use 'col'. Or instead of 'grid-cell', use the BEM friendly 'grid__cell'.

### PR DESCRIPTION
**Pull request by patrickcate**
I need this functionality for a project, so I went ahead and adding it. From my testing it works fine.

Resolves #3

### CODE REVIEW

**Comment by tszarzynski** [comment]
I'll try to review asap.

**Comment by tszarzynski** [comment]
I like the idea here, but I think the implementation is little bit overcomplicated. I'd suggest simplifying it to variables:

`$im-grid-class: 'grid' !default; $im-grid-cell-class: 'grid-cell' !default;`

**Comment by tszarzynski** [comment]
I like the idea here, but I think the implementation is little bit overcomplicated. I'd suggest simplifying it to variables:

```
$im-grid-class: 'grid' !default; 
$im-grid-cell-class: 'grid-cell' !default;
```

With that i'd remove all occurrences of:

`.#{$im-grid-class}#{$im-grid-cell-class}`

as they only make the code less readable and do not introduce any extra functionality. Unless I'm missing something here? What do you think?

**Comment by patrickcate** [comment]
I don't see a downside to your suggestion. I agree it will make things a little more readable.

**Comment by patrickcate** [comment]
Looking over the code more carefully, the only place I see where your suggestion would be a problem is with:

````/*
    Flexible cells
*/
.#{$im-grid-class}--flex#{$im-grid-cell-class} > .#{$im-grid-class}#{$im-grid-cell-class} {
    display: flex;
}
````

specifically with this selector:

````
.#{$im-grid-class}--flex#{$im-grid-cell-class}
````

perhaps that could be simplified to just:

````
.#{$im-grid-class}--flex
````

?

**Comment by tszarzynski** [comment]
Sounds good to me. I'd keep old version of this rule so we don't introduce breaking changes.

**Pull request merged**
